name: publish-nuget

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: publishnuget
    name: Upload nuget to Nuget.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET}}
          
      - name: Build solution and generate NuGet package for Autojector
        run: |
          cd src/Autojector
          dotnet build --configuration Release
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry for Autojector
        run: dotnet nuget push --api-key ${{ secrets.NUGET }} ./src/Autojector/out/*.nupkg --skip-duplicate --no-symbols true --source https://api.nuget.org/v3/index.json