name: publish-nuget

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: publishnuget
    name: Upload nuget to Nuget.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET}}
          
      - name: Build solution and generate NuGet package for Autojector.Abstractions
        run: |  
          pwd
          ls -la
          cd src
          pwd
          ls -la
          cd Autojector.Abstractions
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry for Autojector.Abstractions
        run: dotnet nuget push ./src/Autojector.Abstractions/out/*.nupkg --skip-duplicate --no-symbols true
          
      - name: Build solution and generate NuGet package for Autojector
        run: |
          pwd
          cd ..
          cd ..  
          ls -la
          cd /src/Autojector
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry for Autojector
        run: dotnet nuget push ./src/Autojector/out/*.nupkg --skip-duplicate --no-symbols true

